---
title: Submissions
--- 


The program of the workshop consists of four one-hour invited talks plus a number of short (20 min.) contributed talks and a poster session.

If you wish to contribute a talk or poster, please submit an extended abstract of it via our EasyChair Submission link.

<!--Submissions will be reviewed and accepted by the Programme Committee. In order to be accepted for the conference, submissions must contain original and interesting research in the area of discrete mathematics. If too many acceptable talks are submitted, the [Programme Committee](committees.qmd#scientific-committee) may ask some of them to be presented as posters instead.-->

Submissions will be reviewed and accepted by the Program Committee. In order to be accepted for the conference, submissions must contain original and interesting research in the area of discrete mathematics. The results presented in a submission should not have been published (on-line or in print) in a journal or in peer-reviewed conference proceedings in 2025 or earlier. Simultaneous submission of a full version of your contribution to a journal or another conference is acceptable. 

If too many acceptable talks are submitted, the [Programme Committee](committees.qmd#scientific-committee) may ask some of them to be presented as posters instead.

After the submissions have been reviewed by the Program Committee, source LaTeX files of final versions of accepted submissions must be sent to the conference email address (dmd2026@ugr.es) before the deadline provided [here](index.qmd#important-dates).

Abstracts of accepted talks and posters will be made available at the web of the workshop and extended abstracts will be later published by Birkäuser (Research Perspectives).

Extended abstracts must use our template LaTeX format and are limited to a maximum of **five pages** including references (template available [here](DMD2026_LaTeX_template.zip)).

Submissions are done through the [EasyChair platform](https://easychair.org/conferences/?conf=dmd2026). 

### Talks

- Alberto Espuny Díaz, António Girão, Bertille Granet and Gal Kronenberg. Sublinear degree conditions for 2-factors with k cycles in Hamiltonian graphs
- Alejandro Galván, Jordi Castellví, Richard Coll, Clément Requilé and Juanjo Rué. Enumeration of maximal $K_5$-minor free graphs
- Alexey Gordeev. Bollobás–Meir TSP Conjecture Holds Asymptotically
- Amanda Montejano, Luis Montejano and Oriol Serra. Discrete Brunn--Minkowski inequalities
- Antonio Jesús Lorite Lopez, Daniel Camazon Portela and Juan Antonio Lopez Ramos. A Geometric Approach to Codes from Simplicial Complexes over $F_2$
- Arnau Messegué and Josep M. Miret. There do not exist almost Moore digraphs of odd prime diameter
- Cameron Strachan and Konrad Swanepoel. The number of occurrences of the two smallest distances
- Cristina Fernández-Córdoba, Sergi Sanchez Aragon and Mercè Villanueva. Hamming and homogeneous weight distributions of MacDonald codes over finite chain rings
- Cyril Banderier and Michael Drmota. Combinatorics and Asymptotics of Systems of Linear Catalytic Equations
- Danai Deligeorgaki and Krishna Menon. How to bounce your canon permutation
- Daniel Camazón Portela and Juan Antonio Lopez Ramos. Semigroup action based on skew polynomial evaluation with applications to Cryptography
- David Alcántara, Jette Gutzeit, Torben Donzelmann and Vincent Pilaud. Shade Polytopes
- Delia Garijo, Andrew Goodall and Anna De Mier. Graph invariants from counting homomorphisms to Cayley graphs
- Egor Bakaev and Amir Yehudayoff. A note on the affine plank conjecture
- Emmanuel Briand. Tridimensional rook placements and partial Latin rectangles through multisymmetric functions (extended abstract)
- Francisco Javier Soto Sánchez. Local directed structure of algebraic Cayley digraphs over finite fields
- Gergely Kiss. Cylinder type and $p$-divisible sets in $\mathbb{F}_p^3$
- Gordian Bruns, Dheer Noal Desai, Alexander Gavrilyuk, Josias Gomez and Nathan Lindzey. Intersecting Families of Spanning Trees of $K_{n,n}$
- Gyula Károlyi. On set addition with restricted restrictions
- Hoi Ping Luk, Roman Nedela and Christopher Purcell. Tiling the sphere with regular polygons
- Hoory Shlomo and Daniel Kotlar. On the equal sum partition problem
- Jack Allsop and Patrick Morris. Substructures in random Latin squares
- Jean Cardinal and Micha Sharir. Implicit representations via the polynomial method
- John Bamberg and Lukas Klawuhn. Designs of perfect matchings
- José Gómez Torrecillas, F. J. Lobillo and Gabriel Navarro. A knapsack McEliece-based public key cryptosystem
- Kerri Morgan and Lluis Vena. On the chromatic unicity of wheels: characterizing all the cases
- Lidia Gordo Malagón and María A. Hernández Cifre. On successive minima and successive radii
- Marta Pavelka and Bruno Benedetti. Line-Hamiltonian Polytopes
- Monica Blanco, Francisco Criado and Francisco Santos. Coloopless Zonotopes and Counterexamples to the Shifted Lonely Runner Conjecture
- Pablo Candela, Diego González-Sánchez and Balázs Szegedy. An algorithmic spectral approach to higher-order Fourier analysis
- Patrick Morris, Eion Mulrenin, Maya Sankar and Liana Yepremyan. Variants of Folkman numbers
- Patrick Morris, Miquel Ortega and Juanjo Rue Juanjo Rue. Counting subsets of integers with no arithmetic progression of a given length
- Pierre Aboulker, Charbit Pierre, Coulomb Samuel, Nurse Kathryn and Picasarri-Arrieta Lucas. Acyclic dichromatic number of tournaments:\\these are the champions
- R. Beltrán, J.M. Díaz-Báñez, J.M. Higes, A.J. Lozano, M.A. Pérez-Cutiño and I. Ventura. The shortest marsupial path in a simple polygon
- Ralihe Raul Villagran Olivas. Sandpile groups of strongly regular graphs and the algebraic co-rank of twin-free graphs
- Ruben Rodriguez and Umberto Martinez. On the structure of Polynomial Ideal Codes and Nonlinear Reed--Solomon Codes.
- Sergio Cabello, Timothy M. Chan and Panos Giannopoulos. Delaunay triangulations with predictions
- Sylwia Antoniuk, Alberto Espuny Díaz, Kalina Petrova and Miloš Stojaković. Efficient construction of small subgraphs in the random graph process
- Tabriz Popatia, Simeon Ball and Michel Lavrauw. Additive codes, finite geometry, and Griesmer-type bounds
- Tássio Naia, Guillem Perarnau and Xavier Povill. Balanced subtournaments of a random tournament
- Thomas Lesgourgues, Michelle Delcourt and Luke Postle. Fractional Clique Decompositions of Dense Hypergraphs
- Yan Alves Radtke. On the surjectivity of a map by Kapranov and Voevodsky in four dimensions


### Posters

- Federico Castillo Castillo, Daniel Duarte, Maximiliano Leyton-Alvarez and Alvaro Liendo. On a computational approach to the Nash blowup problem
- Filip Filipi. Generalized snarks for 2-vertex multigraphs with semi-edges
- Gabriela Araujo-Pardo and Leonardo Martinez-Sandoval. On the arc chromatic number for Galois projective planes, affine planes and Euclidean grids. The fractional version for projective planes.
- Gabriela Araujo-Pardo, Julián Fresán-Figueroa, Linda Lesniak and Mika Olsen. Rainbow-free colorings of generalized quadrangles
- Gabriela Araujo-Pardo, Narda Cordero-Michel, Diego Gonzalez and Carmen Hernando. On locating and neighbor-locating colorings of Moore cages
- Ignacio García-Marco, Philippe Gimenez and Mario González-Sánchez. From sumsets to Castelnuvo-Mumford regularity of toric varieties
- Linxuan Li. Fans Arising from Lattice Polytopes of Mixed Volume One and Their Generalizations
- Luis Gustavo Da Soledade Gonzaga and Christiane Neme Campos. On improper colourings of apart-planar graphs
- María A. Hernández Cifre, Víctor Jiménez López and Mario Ruiz Amor. On the Minkowski-Hlawka theorem
- Max Kölbl. Toward a lattice interpretation of the roots of Ehrhart polynomials
- Michal Černý, Miroslav Rada and Ondřej Sokol. Complexity of MaxVar and cliques in a random intersection graph
- Robin Simoens and Steven Van Overberghe. An algorithm to find cospectral mates
- Sandor Ernesto Tuñón Andrés, Alejandro Estrada Moreno and Juan Alberto Rodríguez Velázquez. The Equidistant Dimension of Corona Product Graphs
- Sara Asensio, Ignacio García-Marco and Philippe Gimenez. On the special shape of some Betti diagrams of edge ideals
- Simeon Ball and Robin Simoens. Mutually entangled quantum Latin squares
- Víctor Franco Sánchez, Mercé Mora and María Luz Puertas. Metric representations of graphs: minimality and computational complexity
